package net.iquesoft.iquephoto.core.editor.enums;

public enum EditorCommand {
    NONE, FILTERS, ADJUST, OVERLAY, STICKERS, FRAMES, TEXT, DRAWING, TILT_SHIFT_RADIAL, TILT_SHIFT_LINEAR, VIGNETTE, BRIGHTNESS,
    CONTRAST, SATURATION, WARMTH, EXPOSURE, SHADOWS, TINT, FADE, TRANSFORM, TRANSFORM_VERTICAL, TRANSFORM_HORIZONTAL,
    TRANSFORM_STRAIGHTEN;
}
